seed = 69 # pefect seed
first = true # whether to download input.txt and initiate tokenizer

# data
epoch = 30
train = 0.8
test = 0.2
V = 2048  # vocablury size
L = 256   # Max input len
B = 64    # Batch size

# optimizer
Lr = 3e-4 # learning rate

# model
D = 384   # Input dimension
H = 2     # num of attention heads
N = 8     # Number of transformer blocks
Dh = 512  # Dimension for ffn

# sampling
tmp = 0.8
p = 0.9
gen_len = 100
